language: python
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
    - pip install -e .[test] # install package + test dependencies
script:
    - pytest -s --cov=time_series_predictor tests/ # run tests
after_success:
  - codecov # submit coverage